#ifndef PROCESSINGFRAMEWORK_SDK_GLOBAL_H
#define PROCESSINGFRAMEWORK_SDK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SDK_LIBRARY)
#  define PROCESSINGFRAMEWORK_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROCESSINGFRAMEWORK_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SDK_GLOBAL_H
