#ifndef PROPERTYEDITOR_GLOBAL_H
#define PROPERTYEDITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROPERTYEDITOR_LIBRARY)
#  define PROPERTYEDITORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROPERTYEDITORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTYEDITOR_GLOBAL_H
