#ifndef SCRIPTEDITOR_GLOBAL_H
#define SCRIPTEDITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCRIPTEDITOR_LIBRARY)
#  define SCRIPTEDITORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SCRIPTEDITORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SCRIPTEDITOR_GLOBAL_H
